mdw_demo_homepage:
    path:     /hello/{name}
    defaults: { _controller: MDWDemoBundle:Default:index }
    
articulos:
    pattern: /articulos
    defaults: { _controller: MDWDemoBundle:Default:articulos }
